<footer class="footer"/>

  <section class="footerLinks grid-4">
    <span class="footerTitle">Links</span>
    <span class="footerLink"><a href="">Home</a></span>
    <span class="footerLink"><a href="">About</a></span>
    <span class="footerLink"><a href="">Advertise</a></span>
    <span class="footerLink"><a href="">Subscribe</a></span>
    <span class="footerLink"><a href="">Contact</a></span>
  </section>

  <section class="footerLinks grid-4">
    <span class="footerTitle">Sections</span>
    <span class="footerLink"><a href="">Marketplace</a></span>
    <span class="footerLink"><a href="">Newsroom</a></span>
    <span class="footerLink"><a href="">Top 5</a></span>
    <span class="footerLink"><a href="">Jetset TV</a></span>
    <span class="footerLink"><a href="">Shop</a></span>
  </section>

  <section class="footerLinks grid-4">
    <span class="footerTitle">Content</span>
    <span class="footerLink"><a href="">Categories</a></span>
    <span class="footerLink"><a href="">Interviews</a></span>
    <span class="footerLink"><a href="">Events</a></span>
    <span class="footerLink"><a href="">E-News</a></span>
    <span class="footerLink"><a href="">Issue Archive</a></span>
  </section>

  <section class="footerLinks grid-4">
    <span class="footerTitle">Meta</span>
    <span class="footerLink"><a href="">Sitemap</a></span>
    <span class="footerLink"><a href="">Privacy Policy</a></span>
    <span class="footerLink"><a href="">View Current Issue</a></span>
    <span class="footerLink"><a href="">Login/Logout</a></span>
    <span class="footerLink"><a href="">My Account</a></span>
  </section>



  <section class="copyright">Copyright 2013 Jetset Magazine, LLC &middot; <a class="fLink" target="_blank" href="https://maps.google.com/maps?expflags=enable_star_based_justifications:true&ie=UTF8&cid=10421266078860304962&q=Jetset+Magazine&iwloc=A&gl=US&hl=en">15220 N. 75th St. Scottsdale, AZ 85260</a> &middot; <a class="tel" href="tel:8775385738">877.538.5738</a> &middot; <a class="fLink" href="/privacy">Privacy Policy</a></section>

</footer>
