  <div class="headerBar">
    <div class="topLogo"></div>
    

  </div>

<?php include 'topbanner.inc'; ?>


<!-- Navigation -->

<div class="mainNav">

<ul>
<li><a href="#">Home</a></li>
<li><a href="#">About</a></li>
<li><a onclick="return false;" id="category">Categories</a></li>
<li><a href="http://www.jetsetmag.com/classifieds-backup/classifieds/">Marketplace</a></li>
<li><a href="#">Newsroom</a></li>
<li><a href="#">Top5</a></li>
<li><a href="#">Jetset TV</a></li>
<li><a href="#">Events</a></li>
<li><a href="#">Subscribe</a></li>
<li><a href="#">Advertise</a></li>
<li><a href="#">Contact</a></li>
</ul>

<div class="catNav">
<div class="catNavFade">

      <ul id="sdt_menu" class="sdt_menu">

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Art</div>
              <div class="catImg"><img src="images/nav/art.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Autos</div>
              <div class="catImg"><img src="images/nav/autos.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Aviation</div>
              <div class="catImg"><img src="images/nav/aviation.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Dining</div>
              <div class="catImg"><img src="images/nav/dining.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Executive</div>
              <div class="catImg"><img src="images/nav/executive.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Fashion</div>
              <div class="catImg"><img src="images/nav/fashion.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Golf</div>
              <div class="catImg"><img src="images/nav/golf.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Health</div>
              <div class="catImg"><img src="images/nav/health.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Home Decor</div>
              <div class="catImg"><img src="images/nav/home.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Outdoors</div>
              <div class="catImg"><img src="images/nav/outdoors.jpg" alt=""/></div>
            </a>
          </div>
        </li>
        
        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Real Estate</div>
              <div class="catImg"><img src="images/nav/real-estate.jpg" alt=""/></div>
            </a>
          </div>
        </li>
       
        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Travel</div>
              <div class="catImg"><img src="images/nav/travel.jpg" alt=""/></div>
            </a>
          </div>
        </li>
       
        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Watches &amp; Jewelry</div>
              <div class="catImg"><img src="images/nav/watches.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Wine &amp; Spirits</div>
              <div class="catImg"><img src="images/nav/wine.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Yachts</div>
              <div class="catImg"><img src="images/nav/yachts.jpg" alt=""/></div>
            </a>
          </div>
        </li>
      </ul>


</div> <!--CatNavFade-->
</div><!--catNav-->


</div><!-- mainNav-->

<!-- END Navigation -->