  <div class="topSlider">

        <!-- Slides Container -->
        <div u="slides" id="slidecontain" style="position: absolute; top: 119px; width:1180px; height: 400px; overflow: hidden;">
            <div>
                <img src="http://www.jetsetmag.com/ads/index/top/ad1.jpg" class="topslidewidth" />
                <div u="thumb">
                    <img class="i" src="http://www.jetsetmag.com/ads/index/sidebar/ad1.jpg" style="width:345px; height:345px;" />
                </div>
            </div>
            <div>
                <img src="http://www.jetsetmag.com/ads/index/top/ad2.jpg" class="topslidewidth" />
                <div u="thumb">
                    <img class="i" src="http://www.jetsetmag.com/ads/index/sidebar/ad3.jpg" style="width:345px; height:345px;" />
                </div>
            </div>
            <div>
                <A href="#"><img src="http://www.jetsetmag.com/ads/index/top/ad3.jpg" class="topslidewidth" /></a>
                <div u="thumb">
                    <img class="i" src="http://www.jetsetmag.com/ads/index/sidebar/ad4.jpg" style="width:345px; height:345px;" />
                </div>
            </div>
            <div>
                <img src="http://www.jetsetmag.com/ads/index/top/ad4.jpg" class="topslidewidth" />
                <div u="thumb">
                    <img class="i" src="http://www.jetsetmag.com/ads/index/sidebar/ad5.jpg" style="width:345px; height:345px;" />
                </div>
            </div>
            <div>
                <img src="http://www.jetsetmag.com/ads/index/top/ad5.jpg" class="topslidewidth" />
                <div u="thumb">
                    <img class="i" src="http://www.jetsetmag.com/ads/index/sidebar/ad2.jpg" style="width:345px; height:345px;" />
                </div>
            </div>
        </div>
        
  </div>

<script type="text/javascript" src="http://www.dev.jetsetmag.com/js/beautiful.js"></script>

<!--top ad-->
