<div class="container-16" id="slider1_container" style="">
<div class="grid-16" style="margin-bottom:7px;" id="headerHeight">


  <div class="headerBar">
    <div class="topLogo"></div>
    

  </div>

<?php include 'marketplace-topbanner.inc'; ?>
<script type="text/javascript" src="http://www.dev.jetsetmag.com/js/global.js"></script>
<style type="text/css">
.catContain{width: 125px;}
</style>

<!-- Navigation -->

<div class="mainNav">

<ul>
<li><a href="#">Home</a></li>
<li><a href="#">About</a></li>
<li><a href="http://www.dev.jetsetmag.com/rdw-index.html#categories">Categories</a></li>
<li><a href="#">Marketplace</a></li>
<li><a href="#">Newsroom</a></li>
<li><a href="#">Top5</a></li>
<li><a href="#">Jetset TV</a></li>
<li><a href="#">Events</a></li>
<li><a href="#">Subscribe</a></li>
<li><a href="#">Advertise</a></li>
<li><a href="#">Contact</a></li>
</ul>

</div><!-- mainNav-->

<div class="marketplaceNav">
<div class="marketplaceNavFade">

      <ul id="sdt_menu" class="sdt_menu">

       <li>
          <div class="mktCatContain aviation">
            <a href="#aviation" onClick="return false;">
              <div class="mktImg"><img src="http://www.dev.jetsetmag.com/images/marketplace/airplane.png" alt=""/><br/><span>Aviation</span></div>
            </a>
          </div>
        </li>

        <li>
          <div class="mktCatContain heli">
            <a href="javascript:void(0);" onClick="return false;">
              <div class="mktImg"><img src="http://www.dev.jetsetmag.com/images/marketplace/heli.png" alt=""/><br/><span>Helicopters</span></div>
            </a>
          </div>
        </li>

        <li>
          <div class="mktCatContain autos">
            <a href="javascript:void(0);" onClick="return false;">
              <div class="mktImg"><img src="http://www.dev.jetsetmag.com/images/marketplace/autos.png" alt=""/><br/><span>Autos</span></div>
            </a>
          </div>
        </li>

        <li>
          <div class="mktCatContain realestate">
            <a href="javascript:void(0);" onClick="return false;">
              <div class="mktImg"><img src="http://www.dev.jetsetmag.com/images/marketplace/realestate.png" alt=""/><br/><span>Real Estate</span></div>
            </a>
          </div>
        </li>

        <li>
          <div class="mktCatContain yachts">
            <a href="javascript:void(0);" onClick="return false;">
              <div class="mktImg"><img src="http://www.dev.jetsetmag.com/images/marketplace/yachts.png" alt=""/><br/><span>Yachts</span></div>
            </a>
          </div>
        </li>

        <li>
          <div class="mktCatContain watches">
            <a href="javascript:void(0);" onClick="return false;">
              <div class="mktImg"><img src="http://www.dev.jetsetmag.com/images/marketplace/watches.png" alt=""/><br/><span>Watches &amp; Jewelry</span></div>
            </a>
          </div>
        </li>

        <li>
          <div class="mktCatContain motorcycles">
            <a href="javascript:void(0);" onClick="return false;">
              <div class="mktImg"><img src="http://www.dev.jetsetmag.com/images/marketplace/motorcycles.png" alt=""/><br/><span>Motorcycles</span></div>
            </a>
          </div>
        </li>

        <li>
          <div class="mktCatContain travel">
            <a href="javascript:void(0);" onClick="return false;">
              <div class="mktImg"><img src="http://www.dev.jetsetmag.com/images/marketplace/travel.png" alt=""/><br/><span>Travel</span></div>
            </a>
          </div>
        </li>

        <li>
          <div class="mktCatContain art">
            <a href="javascript:void(0);" onClick="return false;">
              <div class="mktImg"><img src="http://www.dev.jetsetmag.com/images/marketplace/art.png" alt=""/><br/><span>Art</span></div>
            </a>
          </div>
        </li>

      </ul>


</div> <!--CatNavFade-->
</div><!--catNav-->

<div class="mktSearchContain" id="aviation"></div>

<div class="mktSearchContain" id="heli"></div>

<div class="mktSearchContain" id="autos"></div>

<div class="mktSearchContain" id="real"></div>

<div class="mktSearchContain" id="yachts"></div>

<div class="mktSearchContain" id="watches"></div>

<div class="mktSearchContain" id="motorcycles"></div>

<div class="mktSearchContain" id="travel"></div>

<div class="mktSearchContain" id="art"></div>


<!-- END Navigation -->

</div><!-- end container 16-->
</div><!-- end container 16-->