<!--scrolling side ad-->
    <div class="side-ad">

        <!-- ThumbnailNavigator Skin Begin -->
        <div u="thumbnavigator" class="slider1-T" style="position: static; width: 350px; height: 350px; ">
            <!--<div style=" background-color: #000; filter:alpha(opacity=30); opacity:.3; width: 100%; height:100%;"></div>-->

            <!-- Thumbnail Item Skin Begin -->
            <div u="slides" style="height:350px!important;position:static; margin-top:-350px;left:0px!important; width:350px!important;">
                <div u="prototype" class="p" style="POSITION: absolute; WIDTH: 350px; HEIGHT: 350px; TOP: 0; LEFT: 0;">
                    <ThumbnailTemplate style=" WIDTH: 100%; HEIGHT: 100%; border: none;position:absolute; TOP: 0; LEFT: 0;"></ThumbnailTemplate>
                </div>
            </div>
            <!-- Thumbnail Item Skin End -->
        </div>
        <!-- ThumbnailNavigator Skin End -->

    </div><!-- END Scrolling SideAd-->

    <!--roundabout-->

<?php include 'roundabout.inc'; ?>

<br/>

<div class="floatWrap"><!-- Floating Box Wrapper -->
<div class="float" style="top: 0px;"><!-- Floating Box -->

  <img src="images/burberry1.jpg" class="staticAd" /> <!--static ad-->
  <img src="images/burberry2.jpg" class="staticAd" /> <!--static 350 x 95 ad-->

</div><!-- End Floating Box -->
</div><!-- End Floatwrap-->
