<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<html xmlns="http://www.w3.org/1999/xhtml"
    version="XHTML+RDFa 1.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.w3.org/1999/xhtml
    http://www.w3.org/MarkUp/SCHEMA/xhtml-rdfa-2.xsd"
    lang="en-US"
    xml:lang="en-US"
    dir="ltr"
    xmlns:og="http://opengraphprotocol.org/schema/"
    xmlns:fb="http://www.facebook.com/2008/fbml"
>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<!-- Meta -->
<meta name="msvalidate.01" content="BE6B07CFCAE9A97DCFB0D7B999231CCF" />
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />

<title><?php echo $tpTitle ?></title>
<meta name="description" content="<?php echo $pgDesc ?>"></meta>
<meta name="keywords" content="<?php echo $pgKeywords ?>"></meta><meta name="viewport" content="width=device-width">
<meta property="og:title" content="<?php echo $tpTitle ?>" />
<meta property="og:description" content="<?php echo $pgDesc ?>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<?php echo $actual_link ?>" />
<meta property="og:image" content="<?php echo $pgThumb ?>" />

<!-- End Meta -->

<link rel="stylesheet" href="http://www.jetsetmag.com/dev/css/reset.css">
<link rel="stylesheet" href="http://www.jetsetmag.com/dev/css/rwdgrid.css">
<link rel="stylesheet" href="http://www.jetsetmag.com/dev/css/style.css">

<!--[if !IE]> -->
<style type="text/css">
.mainNav li{font-size: 18px;margin-right: 7px; margin-left: 2px;}
</style>
<!-- <![endif]-->

<!-- html5.js for IE less than 9 -->
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!-- css3-mediaqueries.js for IE less than 9 -->
<!--[if lt IE 9]>
  <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
<![endif]-->

<!--Initial Load Scripts -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script type="text/javascript">$('.catLink').each(function() {$(this).prev('.catImg').animate({opacity: "show", top:"100", width:"75px", height:"75px"}, "fast");$(this).prev('.catImg').animate({opacity: "hide", top:"0", width:"0px", height:"0px"}, "fast");});</script>
<!--End Initial Load Scripts -->

<!-- Favicons -->
  <link rel="shortcut icon" href="images/favicon.ico">
  <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
  <link rel="shortcut icon" href="http://www.jetsetmag.com/favicon.ico" />
  <link rel="icon" type="image/gif" href="http://www.jetsetmag.com/j.gif" />
<!-- End Favicons -->


<!-- Start Alexa Certify Javascript -->
<script type="text/javascript" src="https://d31qbv1cthcecs.cloudfront.net/atrk.js"></script>
<script type="text/javascript">_atrk_opts = { atrk_acct: "Esmef1aMIw00yd", domain:"jetsetmag.com"}; atrk ();</script>
<!-- End Alexa Certify Javascript -->

<!-- ClickMeter.com page views tracking: Aviation Category - Main Site -->
<script type='text/javascript'>var ClickMeter_pixel_url = '<?php echo $trackingPixelUrl ?>';</script>
<script type='text/javascript' id='cmpixelscript' src='https://www.clickmeter.com/js/pixel.js'></script>
<noscript><img height='0' width='0' alt='' src='<?php echo $trackingPixelUrl ?>' /></noscript>
<!-- END ClickMeter.com page views tracking: Aviation Category - Main Site -->

</head>
<body>

<div class="container-16" id="slider1_container" style="display:none;">

<div class="grid-16" style="margin-bottom:7px;" id="headerHeight">




  


  <div class="headerBar">
    <div class="topLogo"></div>
    

  </div>


<?php include 'http://www.jetsetmag.com/dev/topbanner.inc'; ?>

<!-- Navigation -->

<div class="mainNav">

<ul>
<li><a href="http://www.jetsetmag.com/dev/rdw-index.html">Home</a></li>
<li><a href="#">About</a></li>
<li><a onclick="return false;" id="category">Categories</a></li>
<li><a href="http://www.jetsetmag.com/classifieds-backup/classifieds/">Marketplace</a></li>
<li><a href="#">Newsroom</a></li>
<li><a href="#">Top5</a></li>
<li><a href="#">Jetset TV</a></li>
<li><a href="#">Events</a></li>
<li><a href="#">Subscribe</a></li>
<li><a href="#">Advertise</a></li>
<li><a href="#">Contact</a></li>
</ul>

<div class="catNav">
<div class="catNavFade">

      <ul id="sdt_menu" class="sdt_menu">

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Art</div>
              <div class="catImg"><img src="http://www.jetsetmag.com/dev/images/nav/art.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Autos</div>
              <div class="catImg"><img src="http://www.jetsetmag.com/dev/images/nav/autos.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Aviation</div>
              <div class="catImg"><img src="http://www.jetsetmag.com/dev/images/nav/aviation.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Dining</div>
              <div class="catImg"><img src="http://www.jetsetmag.com/dev/images/nav/dining.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Executive</div>
              <div class="catImg"><img src="http://www.jetsetmag.com/dev/images/nav/executive.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Fashion</div>
              <div class="catImg"><img src="http://www.jetsetmag.com/dev/images/nav/fashion.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Golf</div>
              <div class="catImg"><img src="http://www.jetsetmag.com/dev/images/nav/golf.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Health</div>
              <div class="catImg"><img src="http://www.jetsetmag.com/dev/images/nav/health.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Home Decor</div>
              <div class="catImg"><img src="http://www.jetsetmag.com/dev/images/nav/home.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Outdoors</div>
              <div class="catImg"><img src="http://www.jetsetmag.com/dev/images/nav/outdoors.jpg" alt=""/></div>
            </a>
          </div>
        </li>
        
        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Real Estate</div>
              <div class="catImg"><img src="http://www.jetsetmag.com/dev/images/nav/real-estate.jpg" alt=""/></div>
            </a>
          </div>
        </li>
       
        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Travel</div>
              <div class="catImg"><img src="http://www.jetsetmag.com/dev/images/nav/travel.jpg" alt=""/></div>
            </a>
          </div>
        </li>
       
        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Watches &amp; Jewelry</div>
              <div class="catImg"><img src="http://www.jetsetmag.com/dev/images/nav/watches.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Wine &amp; Spirits</div>
              <div class="catImg"><img src="http://www.jetsetmag.com/dev/images/nav/wine.jpg" alt=""/></div>
            </a>
          </div>
        </li>

        <li>
          <div class="catContain">
            <a href="#">
              <div class="catLink">Yachts</div>
              <div class="catImg"><img src="http://www.jetsetmag.com/dev/images/nav/yachts.jpg" alt=""/></div>
            </a>
          </div>
        </li>
      </ul>


</div> <!--CatNavFade-->
</div><!--catNav-->


</div><!-- mainNav-->

<!-- END Navigation -->