  <!--WEB FEATURE Column-->
    <div class="grid-3" id="getColHeight">

      <ul class="articleImages" id="firstFeatCol">

          <li>
              <a href="http://prevostcar.com/"><img class="articleImg" src="images/prevost.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Prevost</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.trov.com/"><img class="articleImg" src="images/trov.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Trōv</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.beechcraft.com/"><img class="articleImg" src="images/beechcraft.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Beechcraft</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.eurocopterusa.com/index/index.asp"><img class="articleImg" src="images/eurocopter.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Eurocopter</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.marcjacobs.com/"><img class="articleImg" src="images/mj.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Marc Jacobs</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.dragonandthepearls.com/"><img class="articleImg" src="images/dragon-pearls.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Dragon and the Pearl</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://prevostcar.com/"><img class="articleImg" src="images/prevost.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Prevost</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.trov.com/"><img class="articleImg" src="images/trov.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Trōv</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.beechcraft.com/"><img class="articleImg" src="images/beechcraft.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Beechcraft</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

      </ul>


<div class="featureFloat">
<div class="float" style="top: 0px; width:inherit; display:block;"><!-- Floating Box -->

      <ul class="articleImages">

          <li>
              <a href="http://www.eurocopterusa.com/index/index.asp"><img class="articleImg" src="images/eurocopter.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Eurocopter</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.marcjacobs.com/"><img class="articleImg" src="images/mj.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Marc Jacobs</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.dragonandthepearls.com/"><img class="articleImg" src="images/dragon-pearls.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Dragon and the Pearl</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

      </ul>

    </div>
  </div>

    </div>
  <!-- END WEB FEATURE Column -->