

<!--Main Web Feature Column-->
    <div class="grid-3 featureBox" category="featureMain" id="getColHeight">

      <ul class="articleImages" id="firstFeatCol">

          <li>
              <a href="http://prevostcar.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/prevost.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Prevost</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.trov.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/trov.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Trōv</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.beechcraft.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/beechcraft.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Beechcraft</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.eurocopterusa.com/index/index.asp"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/eurocopter.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Eurocopter</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.marcjacobs.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/mj.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Marc Jacobs</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.dragonandthepearls.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/dragon-pearls.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Dragon and the Pearl</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://prevostcar.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/prevost.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Prevost</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.trov.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/trov.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Trōv</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.beechcraft.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/beechcraft.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Beechcraft</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

      </ul>


      <div class="featureFloat">
      <div class="float" style="top: 0px; width:inherit; display:block;"><!-- Floating Box -->

            <ul class="articleImages">

                <li>
                    <a href="http://www.eurocopterusa.com/index/index.asp"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/eurocopter.jpg" />
                    <div class="featureCaption">
                        <p class="captionTitle">Eurocopter</p>
                        <p class="captionText">description</p>
                    </div></a>
                </li>

                <li>
                    <a href="http://www.marcjacobs.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/mj.jpg" />
                    <div class="featureCaption">
                        <p class="captionTitle">Marc Jacobs</p>
                        <p class="captionText">description</p>
                    </div></a>
                </li>

                <li>
                    <a href="http://www.dragonandthepearls.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/dragon-pearls.jpg" />
                    <div class="featureCaption">
                        <p class="captionTitle">Dragon and the Pearl</p>
                        <p class="captionText">description</p>
                    </div></a>
                </li>

            </ul>

      </div>
      </div>
  
</div><!--End Feature Container -->
<!-- END WEB FEATURE Column -->



<!-- AVIATION WEB FEATURES -->

    <div class="grid-3 featureBox" category="featureAviation" id="getColHeight">

      <ul class="articleImages" id="firstFeatCol">

          <li>
              <a href="http://prevostcar.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/prevost.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Prevost</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.trov.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/trov.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Trōv</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.beechcraft.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/beechcraft.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Beechcraft</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.eurocopterusa.com/index/index.asp"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/eurocopter.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Eurocopter</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.marcjacobs.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/mj.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Marc Jacobs</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.dragonandthepearls.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/dragon-pearls.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Dragon and the Pearl</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://prevostcar.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/prevost.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Prevost</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.trov.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/trov.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Trōv</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.beechcraft.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/beechcraft.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Beechcraft</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

      </ul>


      <div class="featureFloat">
      <div class="float" style="top: 0px; width:inherit; display:block;"><!-- Floating Box -->

            <ul class="articleImages">

                <li>
                    <a href="http://www.eurocopterusa.com/index/index.asp"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/eurocopter.jpg" />
                    <div class="featureCaption">
                        <p class="captionTitle">Eurocopter</p>
                        <p class="captionText">description</p>
                    </div></a>
                </li>

                <li>
                    <a href="http://www.marcjacobs.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/mj.jpg" />
                    <div class="featureCaption">
                        <p class="captionTitle">Marc Jacobs</p>
                        <p class="captionText">description</p>
                    </div></a>
                </li>

                <li>
                    <a href="http://www.dragonandthepearls.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/dragon-pearls.jpg" />
                    <div class="featureCaption">
                        <p class="captionTitle">Dragon and the Pearl</p>
                        <p class="captionText">description</p>
                    </div></a>
                </li>

            </ul>

      </div>
      </div>
  
</div><!--End Feature Container -->
<!-- END AVIATION WEB FEATURES -->



<!-- BEGIN ART WEB FEATURES -->

    <div class="grid-3 featureBox" category="featureArt" id="getColHeight">

      <ul class="articleImages" id="firstFeatCol">

          <li>
              <a href="http://prevostcar.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/prevost.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Prevost</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.trov.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/trov.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Trōv</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.beechcraft.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/beechcraft.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Beechcraft</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.eurocopterusa.com/index/index.asp"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/eurocopter.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Eurocopter</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.marcjacobs.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/mj.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Marc Jacobs</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.dragonandthepearls.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/dragon-pearls.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Dragon and the Pearl</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://prevostcar.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/prevost.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Prevost</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.trov.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/trov.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Trōv</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

          <li>
              <a href="http://www.beechcraft.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/beechcraft.jpg" />
              <div class="featureCaption">
                  <p class="captionTitle">Beechcraft</p>
                  <p class="captionText">description</p>
              </div></a>
          </li>

      </ul>


      <div class="featureFloat">
      <div class="float" style="top: 0px; width:inherit; display:block;"><!-- Floating Box -->

            <ul class="articleImages">

                <li>
                    <a href="http://www.eurocopterusa.com/index/index.asp"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/eurocopter.jpg" />
                    <div class="featureCaption">
                        <p class="captionTitle">Eurocopter</p>
                        <p class="captionText">description</p>
                    </div></a>
                </li>

                <li>
                    <a href="http://www.marcjacobs.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/mj.jpg" />
                    <div class="featureCaption">
                        <p class="captionTitle">Marc Jacobs</p>
                        <p class="captionText">description</p>
                    </div></a>
                </li>

                <li>
                    <a href="http://www.dragonandthepearls.com/"><img class="articleImg" src="http://www.jetsetmag.com/dev/images/dragon-pearls.jpg" />
                    <div class="featureCaption">
                        <p class="captionTitle">Dragon and the Pearl</p>
                        <p class="captionText">description</p>
                    </div></a>
                </li>

            </ul>

      </div>
      </div>
  
</div><!--End Feature Container -->
<!-- END ART WEB FEATURES -->






<!--Web Feature Function -->

<script type="text/javascript">
$(document).ready(function () {

    $('div[category="featureMain"]').hide();
    $('div[category="featureArt"]').hide();
    $('div[category="featureAviation"]').hide();

  if(window.location.href.indexOf("rdw-index") > -1) {
    $('.featureBox').hide();
    $('div[category="featureMain"]').show();
    $('div[category="featureArt"]').remove();
    $('div[category="featureAviation"]').remove();
  }

  if(window.location.href.indexOf("/article") > -1) {
    $('.featureBox').hide();
    $('div[category="featureAviation"]').show();
    $('div[category="featureMain"]').remove();
    $('div[category="featureArt"]').remove();

  }

  if(window.location.href.indexOf("/art") > -1) {
    $('.featureBox').hide();
    $('div[category="featureArt"]').show();
    $('div[category="featureMain"]').remove();
    $('div[category="featureAviation"]').remove();
  }


});
</script>
